// interface Post {
//   $id: string;
//   $createdAt: string;
//   content: string;
// }

// //use in the component PostList.tsx
// //any post object must have these fields
// // $ == are fields generated by appwrite
